onlyBuiltDependencies:
  - '@sentry-internal/node-native-stacktrace'
  - cpu-features
  - eslint-plugin-n8n-nodes-base
  - limescape-docs
  - limescape-docs
  - sharp
  - ssh2
  - tesseract.js
  - zerox
