onlyBuiltDependencies:
  - '@google/genai'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry-internal/node-native-stacktrace'
  - cpu-features
  - eslint-plugin-n8n-nodes-base
  - isolated-vm
  - limescape-docs
  - protobufjs
  - sharp
  - ssh2
  - tesseract.js
  - unrs-resolver
